### ISSUE TITLE
Change the "Size" button in EditorSidebar.js to "Row" and create a row menu.

### ISSUE THREAD

**Issue by matthewalunni** [4F00-Group-3/CMS#113]
The editor needs the ability to add columns.  This means we need to change the icon in the EditorSidebar from "Size" to "Row".  It also means that we need to modify the returnPage() method in EditingPage.js, and the returnElement() method in PageSection.js to allow for columns.

**Comment by subonja** [comment]
Random thought- are columns necessary? I have used Wix and the process is similar to what we have; add page sections to the canvas, with one column. Perhaps, we can have a page section or component which is added to the page that offers multiple columns?

If we were to go with columns, how would we go about adding a third or more column? How about deletes; would a delete take out all the content in that column, or would it only delete empty columns?
