### ISSUE TITLE
Create a "User Manual Pages" page

### ISSUE THREAD

**Issue by subonja** [4F00-Group-3/CMS#244]
Different from issue #110, this task is to make a simple react component which will display the User Manual Pages to the user when the user clicks "help" at any point in time through out the site. 

Most likely all you need is an iframe linked to a a url (google doc) or even better, if possible to a location on sandcastle.

**Comment by ParamJansari0** [comment]
This has been moved to the Documentation Project Board

**Comment by subonja** [comment]
Used an iframe that points directly to the user manual in our Google Drive. Need to ensure that pdf stays in the drive.
